apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio-service-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: portfolio
    spec:
      containers:
        - name: portfolio
          image: hoya0220/portfolio-service
          imagePullPolicy: IfNotPresent
  selector:
    matchLabels:
      app: portfolio
---
apiVersion: v1
kind: Service
metadata:
  name: portfolio-service
spec:
  selector:
    app: portfolio
  ports:
    - port: 3000
      targetPort: 3000
  type: ClusterIP
